version: '3.8'

services:
  chatbot:
    build:
      context: ./services/chatbot
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

volumes:
  redis_data:
