# /home/kss/문서/DevOps_Project/services/redis/docker-compose.yml

version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
