version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./app:/app/app
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=7000
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 